import type { Metadata } from "next";
import { Urbanist } from "next/font/google"
import localFont from "next/font/local";
import "./globals.css";

const eugusto = localFont({
  src: "./fonts/Eugusto.otf",
  variable: "--eugusto",
  weight: "100 900",
});

const urbanist = Urbanist({
  subsets: ["latin"],
  variable: "--urbanist",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  fallback: ["Helvetica", "Arial", "sans-serif"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${eugusto.variable} ${urbanist.variable} antialiased font-urbanist`}
      >
        {children}
      </body>
    </html>
  );
}
